### PR TITLE
2-BM and 32-ID streaming data collection improvements

### PR DESCRIPTION
**Pull request by decarlof**
- moved visible light detection PVs to [mctOptics](https://mctoptics.readthedocs.io/en/latest/)
- added support for automatic raw data upload to reconstruction cluster
- stability improvements

### CODE REVIEW

**Comment by decarlof** [comment]
@MarkRivers the only changes in tomoscan.py are [here](https://github.com/decarlof/tomoscan/blob/7b544b35e2a9830d9e082698d705cbe09b7a5d46/tomoscan/tomoscan.py#L102):

```
        self.control_pvs['RotationHomR']           = PV(rotation_pv_name + '.HOMR')
        self.control_pvs['RotationHomF']           = PV(rotation_pv_name + '.HOMF')
        self.control_pvs['RotationSpeedJog']       = PV(rotation_pv_name + '.JVEL')
        self.control_pvs['RotationAccelJog']       = PV(rotation_pv_name + '.JAR')
```
so we can access these PVs to adjust motor speed during streaming (i.e. while rotary is moving).

We can now adjust exposure time (speed) and angular step during streaming = without having to stop the stage.

**Review by MarkRivers — COMMENTED** [review]
This looks OK to me.  tomoscan_pso.py had a wait time changed from 180 to 30.  Is 7BM OK with that?

**Comment by decarlof** [comment]
7BM is OK with it but in general I see now this can be an issue for fast/large camera needing more time to complete the saving. The reason we reduced it is because when we do vertical or mosaic scans and loose a frame (is very rare but sometimes it happens) we don't want to wait 3 min before starting the next scan.

Perhaps we should consider having this extra time variable depending on camera max frame rate and chip size?

**Comment by decarlof** [comment]
Ok this is ready to merge for now.

**Pull request merged**
