### PR TITLE
adding TomoScan2BM, untested

### PR DESCRIPTION
**Pull request by decarlof**
Please keep this open

### CODE REVIEW

**Review by MarkRivers — CHANGES_REQUESTED** [review]
I think that you need this after line 135:
prefix = self.pv_prefixes['PSO']

**Comment by decarlof** [comment]
@MarkRivers is there a VideoMode for FLIR/Oryx ORX-10G-51S5M ? I looked [here](http://softwareservices.flir.com/ORX-10G-51S5/latest/Model/spec.html). If not I know the readout time and can just make a table for the bit formats.

**Comment by MarkRivers** [comment]
I don't think the Oryx has the VideoMode.  To start with you can just return the frame_time for modes you plan to support and flag an error if a non-supported mode is requested.

**Comment by decarlof** [comment]
@MarkRivers ops not sure what I am doing. Not ready to review. All seems to work up to the flyscan. I will look at the file save next.

**Review by MarkRivers — CHANGES_REQUESTED** [review]
Lines 96-98 in tomoscan.py can be moved up to before line 90, i.e. they exist for all Spinnaker cameras.  The only PVs that are camera-dependent begin with GC_.

**Comment by decarlof** [comment]
@MarkRivers Fly scan works but I have problem with dark and white saving in the hdf file (they store in the right location but I only save one of each (see [here](https://drive.google.com/drive/folders/1qAjh0LP6f3jwsvW1QgcpUXecXwavUtcW?usp=sharing) both captured with multiple dark/white). In the old scan script I was setting a total FPNumCapture = (proj + flat + dark) and once FPCapture was set to 'Capture' images were stored in the right location by changing the HDF5Location. Here is cleaner but I am doing something wrong in the collect_static_frames() so I end up collecting only 1 dark/white. Will look at it more later.

**Comment by MarkRivers** [comment]
I have only tested with writing separate HDF5 files.  I will try with writing them all to a single file.

**Comment by decarlof** [comment]
> I have only tested with writing separate HDF5 files. I will try with writing them all to a single file.

On my old version I had to set total FPNumCapture = (proj + flat + dark) to get it to work properly, but I am afraid doing this here will mess the code to accommodate for those  who still want to save in multiple files.

**Comment by MarkRivers** [comment]
I just modified tomoscan_13bm.py to put the darks, flats, and projections in a single file.  I specified 5 darks at start only, 10 flats at start and end, and 360 projections.  This is part of the h5dump output on the file:
```
   GROUP "exchange" {
      DATASET "data" {
         DATATYPE  H5T_STD_U16LE
         DATASPACE  SIMPLE { ( 360, 1200, 1920 ) / ( 385, 1200, 1920 ) }
...
      }
      DATASET "data_dark" {
         DATATYPE  H5T_STD_U16LE
         DATASPACE  SIMPLE { ( 5, 1200, 1920 ) / ( 385, 1200, 1920 ) }
...
      }
      DATASET "data_white" {
         DATATYPE  H5T_STD_U16LE
         DATASPACE  SIMPLE { ( 20, 1200, 1920 ) / ( 385, 1200, 1920 ) }
...
```
So there are 360 projections, 5 darks and 20 flats as expected.

This is the diff of the file that saves everything in one file from the master branch of tomoscan_13bm.py
```

+++ b/tomoscan/tomoscan_13bm.py
@@ -59,7 +59,7 @@ class TomoScan13BM(TomoScan):
             # Set number of MCS channels, NumImages, and NumCapture
             self.epics_pvs['MCSStopAll'].put(1, wait=True)
             self.epics_pvs['MCSNuseAll'].put(num_images, wait=True)
-            self.epics_pvs['FPNumCapture'].put(num_images, wait=True)
+            #self.epics_pvs['FPNumCapture'].put(num_images, wait=True)

         if trigger_mode == 'MCSExternal':
             # Put MCS in external trigger mode
@@ -83,8 +83,8 @@ class TomoScan13BM(TomoScan):
         """
         # This is called when collecting dark fields or flat fields
         self.set_trigger_mode('MCSInternal', num_frames)
-        if save:
-            self.epics_pvs['FPCapture'].put('Capture')
+        #if save:
+        #    self.epics_pvs['FPCapture'].put('Capture')
         self.epics_pvs['CamAcquire'].put('Acquire')
         # Wait for detector and file plugin to be ready
         time.sleep(0.5)
@@ -123,6 +123,24 @@ class TomoScan13BM(TomoScan):
         # exposure time = LNE output width.
         # Need to wait for the exposure time
         time.sleep(self.epics_pvs['ExposureTime'].value)
+
+        # Compute total number of frames to capture
+        num_dark_fields = self.epics_pvs['NumDarkFields'].value
+        dark_field_mode = self.epics_pvs['DarkFieldMode'].get(as_string=True)
+        num_flat_fields = self.epics_pvs['NumFlatFields'].value
+        flat_field_mode = self.epics_pvs['FlatFieldMode'].get(as_string=True)
+        num_angles = self.epics_pvs['NumAngles'].value
+        num_images = num_angles
+        if dark_field_mode not in ('None'):
+            num_images += num_dark_fields;
+        if dark_field_mode == 'Both':
+            num_images += num_dark_fields;
+        if flat_field_mode not in ('None'):
+            num_images += num_flat_fields;
+        if flat_field_mode == 'Both':
+            num_images += num_flat_fields;
+        self.epics_pvs['FPNumCapture'].put(num_images, wait=True)
+        self.epics_pvs['FPCapture'].put('Capture')

     def end_scan(self):
         """Performs the operations needed at the very end of a scan.
@@ -226,7 +244,7 @@ class TomoScan13BM(TomoScan):
         self.epics_pvs['MCSPrescale'].put(prescale, wait=True)
         self.set_trigger_mode('MCSExternal', num_angles)
         # Start capturing in file plugin
-        self.epics_pvs['FPCapture'].put('Capture')
+        #self.epics_pvs['FPCapture'].put('Capture')
         # Start the camera
         self.epics_pvs['CamAcquire'].put('Acquire')
         # Start the MCS
```

**Comment by MarkRivers** [comment]
I think I will add code in the base class begin_scan to set a  number of class variables that give the scan parameters (dark_field_mode, num_dark_fields, total_images, etc.  That can reduce the number of times we need to fetch the PV values.

**Comment by MarkRivers** [comment]
I just pushed up a new file, tomoscan_13bm_single_file.py.  This has the above changes in it so you can see what I did easier.

**Comment by MarkRivers** [comment]
I just modified begin_scan in the base class so it reads the PVs for scan parameters and stores them in class variables.  This really simplifies the code needed in the derived class, and in other places in the base class.

Now the difference between tomo_scan13bm.py (saves in multiple files) and tomoscan_13bm_single_file.py (saves in a single file) is just this.  So it just deletes 5 lines and adds 3 lines.
```
diff --git a/tomoscan/tomoscan_13bm.py b/tomoscan/tomoscan_13bm.py
index 828008e..42cb17c 100644
--- a/tomoscan/tomoscan_13bm.py
+++ b/tomoscan/tomoscan_13bm.py
@@ -59,7 +59,6 @@ class TomoScan13BM(TomoScan):
             # Set number of MCS channels, NumImages, and NumCapture
             self.epics_pvs['MCSStopAll'].put(1, wait=True)
             self.epics_pvs['MCSNuseAll'].put(num_images, wait=True)
-            self.epics_pvs['FPNumCapture'].put(num_images, wait=True)

         if trigger_mode == 'MCSExternal':
             # Put MCS in external trigger mode
@@ -83,8 +82,6 @@ class TomoScan13BM(TomoScan):
         """
         # This is called when collecting dark fields or flat fields
         self.set_trigger_mode('MCSInternal', num_frames)
-        if save:
-            self.epics_pvs['FPCapture'].put('Capture')
         self.epics_pvs['CamAcquire'].put('Acquire')
         # Wait for detector and file plugin to be ready
         time.sleep(0.5)
@@ -123,6 +120,9 @@ class TomoScan13BM(TomoScan):
         # exposure time = LNE output width.
         # Need to wait for the exposure time
         time.sleep(self.epics_pvs['ExposureTime'].value)
+        # Set the total number of frames to capture and start capture on file plugin
+        self.epics_pvs['FPNumCapture'].put(self.total_images, wait=True)
+        self.epics_pvs['FPCapture'].put('Capture')

     def end_scan(self):
         """Performs the operations needed at the very end of a scan.
@@ -225,8 +225,6 @@ class TomoScan13BM(TomoScan):
         prescale = math.floor(abs(rotation_step  * steps_per_deg))
         self.epics_pvs['MCSPrescale'].put(prescale, wait=True)
         self.set_trigger_mode('MCSExternal', num_angles)
-        # Start capturing in file plugin
-        self.epics_pvs['FPCapture'].put('Capture')
         # Start the camera
         self.epics_pvs['CamAcquire'].put('Acquire')
         # Start the MCS
```
I have pushed up a new version of tomoscan.py and tomoscan_13bm_single_file.py.

I have tested this as with the previous version.  It puts 5 darks, 20 flats, and 360 projections in a single HDF5 file.

**Comment by MarkRivers** [comment]
I made one small change to your code.  I moved CamTriggerSource to be created for all PointGrey/FLIR cameras, it is not specific to the Oryx.

I pushed the change.

**Pull request merged**
