### PR TITLE
Add camera gain saving to 7-BM

### PR DESCRIPTION
**Pull request by aps-7bm**
After seeing nonlinearity in the grayscale values from my tomography camera at 7-BM, I have implemented saving of the flatfield images at varying exposure times to /exchange/data_gains in the HDF5 output files.  This update adds this functionality for TomoScan at 7-BM.  My intention is to use these data to derive the camera nonlinearity and use this to correct the grayscale values prior to reconstruction.

### CODE REVIEW

**Comment by MarkRivers** [comment]
When you made those measurements are you sure that Gamma ($(P)$(R)GC_Gamma_RBV) was set to 1.0 or that Gamma Enable ($(P)$(R)GC_GammaEnable) was set to 0?

Also was Black Level ($(P)$(R)GC_BlackLevel) set to 0?

If black level is not 0 or gamma is not 1 that will lead to an apparent non-linearity.

**Comment by aps-7bm** [comment]
The black level was set to zero.  The gamma was enabled and set to 0.8.  I don't believe I have ever changed this setting; why this would be anything other than unity is beyond me.  I'm going to disable gamma.  At this point, I might like to keep the code changes in, since it's cheap insurance against nonlinearities.

**Comment by aps-7bm** [comment]
Good catch, by the way.  There are so many parameters exposed on these cameras that it's a bit of a mess to look through them all.  Thank you.

**Comment by decarlof** [comment]
I cannot find in the generated hdf file, the flat field exposure time interval. This is set [here](https://github.com/aps-7bm/tomoscan/blob/4c2feb51bd1e1168845889c0ab12d1c788dbe3f8/tomoscan/tomoscan_7bm.py#L218) as: 

`gain_exp_times = np.linspace(0, self.epics_pvs['FlatExposureTime'].value, self.num_gain_fields)`

 I think it would be better to have this information stored in the file as self explanatory. One option could be to store it as:

`/exchange/data_gain_exp_times` with attribute "units" = to "s"

(this will also accomodate for an arbitrary exposure time list, not just linear). 

I suggest also to change the attribute of

`/exchange/data_gain`

from (theta:y:x)  to (exp_time:y:x)

**Comment by decarlof** [comment]
I checked our identical camera at 2-BM and it also had 

- Gamma $(P)$(R)GC_Gamma_RBV set to 0.8 and 
- Gamma Enable ($(P)$(R)GC_GammaEnable) was set to 1

It looks this is the default for this camera. If you add agree I will add [here](https://github.com/tomography/tomoscan/blob/2757601c01c5608bf04ad3f79b79082b0e39d73f/tomoscan/tomoscan.py#L144) and if on this model and add these PV so we can set in our init() to 1/0

**Comment by MarkRivers** [comment]
I think it is better to add these lines to the end of st.cmd for the camera.  

dbpf "$(P)$(R)GC_Gamma 1
dbpf "$(P)$(R)GC_GammaEnable 0
dbpf "$(P)$(R)GC_BlackLevel 0

Then Python does not need to know what kind of camera is in use,   You can easily force other GenICam parameters that are not in autosave the same way.

**Comment by aps-7bm** [comment]
I like Mark's suggestion here.  I agree with Francesco that this needs to be hard-coded so it doesn't trip anyone else up.  I think the solution of doing this in the camera IOC so it is just by default set to reasonable settings makes sense.  It will also save us editing of the code if/when we change camera models.

**Comment by decarlof** [comment]
> I think it is better to add these lines to the end of st.cmd for the camera.
> 
> dbpf "$(P)$(R)GC_Gamma 1 dbpf "$(P)$(R)GC_GammaEnable 0 dbpf "$(P)$(R)GC_BlackLevel 0
> 
> Then Python does not need to know what kind of camera is in use, You can easily force other GenICam parameters that are not in autosave the same way.

good suggestion. These should be added after the last line of `st.cmd.base` correct?

**Comment by MarkRivers** [comment]
> These should be added after the last line of st.cmd.base correc?

That's an interesting question.  It is possible that some of these GenICam features are found on some cameras and not others, so they should be in the camera-specific file.

At GSECARS our Spinnaker IOC directories only have st.cmd which contains everything, they don't have separate st.cmd and st.cmd.base.  I only did that in ADSpinnaker so that I could support many models in a single iocSpinnaker directory without lots of repeated commands.  This is an example of one of our Spinnaker IOC directories:
```
corvette:CARS/iocBoot/ioc13ida_pg1>pwd
/home/epics/support/CARS/iocBoot/ioc13ida_pg1
corvette:CARS/iocBoot/ioc13ida_pg1>ls
Makefile  auto_settings.req  autosave  dllPath.bat  envPaths  pgXML.xml  st.cmd  start_epics
```

**Comment by aps-7bm** [comment]
I made those modifications to my st.cmd.oryx_310S9M file.  It now looks like this:

  1 < envPaths
  2 errlogInit(20000)
  3 
  4 dbLoadDatabase("$(TOP)/dbd/ioc7bmrhel8ADLinux.dbd")
  5 ioc7bmrhel8ADLinux_registerRecordDeviceDriver(pdbbase)
  6 
  7 # Use this line for a specific camera by serial number, in this case a BlackFlyS GigE
  8 #epicsEnvSet("CAMERA_ID", "22150530")
  9 epicsEnvSet("CAMERA_ID", "21334235")
 10 #epicsEnvSet("CAMERA_ID", "0")
 11 
 12 epicsEnvSet("GENICAM_DB_FILE", "$(TOP)/db/FLIR_ORX_10G_310S9M.template")
 13 
 14 < st.cmd.base
 15 
 16 # Explicity set gamma, gamma enable, black level, and ADC depth
 17 dbpf "7bmSP1:cam1:GC_Gamma", "1"
 18 dbpf "7bmSP1:cam1:GC_GammaEnable", "0"
 19 dbpf "7bmSP1:cam1:GC_BlackLevel", "0"
 20 dbpf "7bmSP1:cam1:GC_AdcBitDepth", "2"

I have confirmed that on power cycling the camera and restarting the IOC, it sets these PVs correctly.  I know hardcoding the values isn't terribly elegant, but I wasn't sure how to do the macro substitutions.  Are there other PVs besides these that are set by default to silly values?

**Comment by aps-7bm** [comment]
I implemented Francesco's suggestions about adding a dataset (/exchange/gain_exp_times), changing the units on /exchange/data_gains, and adding units to both /exchange/gain_exp_times and /exchange/theta.

**Comment by MarkRivers** [comment]
@aps-7bm here is the startup script I use for my tomography FLIR camera, which uses macros when calling dbpf.  Note that I set the PREFIX environment variable near the beginning and use it throughout.
```
corvette:CARS/iocBoot/ioc13bmd_pg1>more st.cmd
< envPaths
errlogInit(20000)

dbLoadDatabase("$(ADSPINNAKER)/iocs/spinnakerIOC/dbd/spinnakerApp.dbd")
spinnakerApp_registerRecordDeviceDriver(pdbbase)

# Prefix for all records
epicsEnvSet("PREFIX", "13BMDPG1:")
epicsEnvSet("GENICAM_DB_FILE", "$(ADGENICAM)/db/PGR_GS3_U3_23S6M.template")
# Use this line for a specific camera by serial number, in this case the BMD tomography Grasshopper3 USB-3.0 camera
#epicsEnvSet("CAMERA_ID", "14120134")
epicsEnvSet("CAMERA_ID", "17549192")

# The port name for the detector
epicsEnvSet("PORT",   "PG1")
# Really large queue so we can stream to disk at full camera speed
epicsEnvSet("QSIZE",  "2000")
# The maximim image width; used for row profiles in the NDPluginStats plugin
epicsEnvSet("XSIZE",  "2048")
# The maximim image height; used for column profiles in the NDPluginStats plugin
epicsEnvSet("YSIZE",  "2048")
# The maximum number of time series points in the NDPluginStats plugin
epicsEnvSet("NCHANS", "2048")
# The maximum number of frames buffered in the NDPluginCircularBuff plugin
epicsEnvSet("CBUFFS", "500")
# The search path for database files
# This is for Windows
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$(ADCORE)/db;$(ADGENICAM)/db;$(ADSPINNAKER)/db")
# Define NELEMENTS to be enough for a 1920x1200x3 (color) image
epicsEnvSet("NELEMENTS", "7000000")

# ADSpinnakerConfig(const char *portName, const char *cameraId, int numSPBuffers,
#                   size_t maxMemory, int priority, int stackSize)
ADSpinnakerConfig("$(PORT)", $(CAMERA_ID))
asynSetTraceIOMask($(PORT), 0, 2)
# Set ASYN_TRACE_WARNING and ASYN_TRACE_ERROR
#asynSetTraceMask($(PORT), 0, 0xff)
#asynSetTraceFile($(PORT), 0, "asynTrace.out")
#asynSetTraceInfoMask($(PORT), 0, 0xf)

# Main database.  This just loads and modifies ADBase.template
dbLoadRecords("$(ADSPINNAKER)/db/spinnaker.template", "P=$(PREFIX),R=cam1:,PORT=$(PORT)")

# Load the autogenerated file of GenICam features
dbLoadRecords("$(GENICAM_DB_FILE)", "P=$(PREFIX),R=cam1:,PORT=$(PORT)")

# Create a standard arrays plugin
NDStdArraysConfigure("Image1", 5, 0, "$(PORT)", 0, 0)
# Use this line for 8-bit data only
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),TYPE=Int8,FTVL=CHAR,NELEMENTS=$(NELEMENTS)")
# Use this line for 8-bit or 16-bit data
#dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=image1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),TYPE=Int16,FTVL=SHORT,NELEMENTS=$(NELEMENTS)")

# Load all other plugins using commonPlugins.cmd
< $(ADCORE)/iocBoot/commonPlugins.cmd

< ../save_restore_IOCSH.cmd
set_requestfile_path("$(ADGENICAM)/db")
set_requestfile_path("$(ADSPINNAKER)/db")

iocInit()

# save things every thirty seconds
create_monitor_set("auto_settings.req", 30,"P=$(PREFIX)")

# These PVs are in auto_settings.req but don't have PINI=Yes
dbpf("$(PREFIX)cam1:GC_OnBoaColProEna.PROC", "1")
dbpf("$(PREFIX)cam1:GC_VideoMode.PROC", "1")
```

**Comment by decarlof** [comment]
in our case epicsEnvSet("PREFIX", "2bmbSP1:") is set in the st.cmd.base. 

Following @MarkRivers suggestion, I changed after the last line of st.cmd.oryx_51S5:

from:
...
< st.cmd.base

dbpf "2bmbSP1:cam1:GC_Gamma", "1"
dbpf "2bmbSP1:cam1:GC_GammaEnable", "0"
dbpf "2bmbSP1:cam1:GC_BlackLevel", "0"
dbpf "2bmbSP1:cam1:GC_AdcBitDepth", "2"

to:
...
< st.cmd.base

dbpf("$(PREFIX)cam1:GC_Gamma", "1")
dbpf("$(PREFIX)cam1:GC_GammaEnable", "0")
dbpf("$(PREFIX)cam1:GC_BlackLevel", "0")
dbpf("$(PREFIX)cam1:GC_AdcBitDepth", "2")

and all works as expected.

**Comment by decarlof** [comment]
@MarkRivers @aps-7bm I think we can merge this, if you are OK

**Pull request merged**
