### PR TITLE
Addressing #156 #157  #158 #160 #161

### PR DESCRIPTION
**Pull request by decarlof**
#156 Collect a data set without projections
#157  no need to send the rotary stage to the start scan position
#158  direction of the theta array in compute_positions_PSO in tomoscan_pso.py is incorrect
#160 back and forth scan angles are off by one step
#161 adding the last saved file name on the main tomoScan medm screen

### CODE REVIEW

**Comment by decarlof** [comment]
The [above commit](https://github.com/tomography/tomoscan/pull/159/commits/8af3b383dfbf69bb32f7e164b7f4c3f676fc6a3f) is a tempoary fix to #160

**Comment by decarlof** [comment]
@MarkRivers @nikitinvv I am ready to merge if that is OK with you

**Comment by nikitinvv** [comment]
@decarlof it's ok

**Comment by MarkRivers** [comment]
Why does tomoScan.png now show tomoScan_test.adl rather than tomoScan.adl?

**Comment by decarlof** [comment]
that was a mistake only in the png/doc screen shot if the main tomoscan. I just update it. I also notice the top box of the tomoscan.adl screen (Setup) is off by 2 pixel. I will correct in the next

**Comment by MarkRivers** [comment]
This looks fine to me.

**Pull request merged**
