### PR TITLE
small update

### PR DESCRIPTION
**Pull request by decarlof**

### CODE REVIEW

**Comment by decarlof** [comment]
@MarkRivers I tried your approach putting 

`self.epics_pvs['FPCapture'].put('Capture')`

in the begin_scan() but is still not working for me. I think the fact I am switching from internal to external shutter control (it seems your MCSInternal still keeps the camera in external shutter for all type of frames) is the issue.

**Review by MarkRivers — COMMENTED** [review]
Lines 160 to 174 are not needed.  That calculation is now done in the tomoscan.begin_scan.  

Change line 175 to use self.total_images rather than num_images.

**Comment by MarkRivers** [comment]
Can you describe the symptom of the problem you are having in more detail?

**Review by MarkRivers — COMMENTED** [review]
@decarlof here are some more comments that might help.

- I don't understand why you are enabling AutoSave mode in line 33.  That will cause the HDF5 plugin to automatically save files on every callback.  I don't think you want to do that, I would set it to 'No'.

- I think you should remove line 83.  That is probably your problem.  You are setting the number of frames to capture in the HDF5 plugin to be just NumFlats or NumDarks.  You don't want to do that in this function.  You just want to set that to self.total_images in begin_scan().

- The same comment applies to line 102, delete that line as well.

- Repeating my previous review comment, delete lines 160  to 174, and change line 175 to
```
 self.epics_pvs['FPNumCapture'].put(self.total_images, wait=True)
```

- Lines 195 and 196 replace 'FilePath' with 'FilePathRBV' and 'FileName' with 'FileNameRBV'.  This will guarantee that the string concatenation in line 197 works because the RBV PVs have the trailing path separator ('/' on Linux, '\' on Windows).

- Lines 210 to 213 can be deleted because those PVs have already been read into self.rotation_start, etc. in tomoscan.begin_scan().  Add the self. prefix on the variables below that line.  I need to do that for tomoscan_13bm as well.

**Pull request closed without merging**
