### PR TITLE
Added tomoScanStream at 7-BM, energy scan at 32-ID and the ability to take a flat field at a preset angle

### PR DESCRIPTION
**Pull request by decarlof**
This pull request includes the following:

- in the main `tomoscan.py` class: added SampleOutAngle to be able to set an arbitrary angle where to take the flat field. This is useful for flat(er) sample and in particular for the nano CT (slow/limited stage travel). If `SampleOutAngle=0` it behaves as before
- added tomoScanStream at 7-BM
- added energy scan at 32-ID
- standardization of the AD xml files handling at 2-BM, 7-BM and 32-ID
- doc update

### CODE REVIEW

**Comment by MarkRivers** [comment]
I like the idea of having SampleOutAngle.  However, there is a potential problem with having value=0 mean ignore it.  If FlatFieldMode=Both then it will normally take the flat fields at 0 degrees and 180 degrees.  I have had the case where 0 degrees is OK to take the flat field, but 180 is not.  With the proposed scheme I could not specify that I want flat fields taken only at 0 degrees, both before and after the scan.  One solution would be to use -1 as the flat that means ignore SampleOutAngle.  Maybe there are better ideas.

**Comment by decarlof** [comment]
good point. How about adding a check box, when set  flats are taken only at the specified angle,

**Comment by MarkRivers** [comment]
medm does not have a checkbox widget unfortunately, so it would have to be a bo record with a menu or radio button.

**Comment by nikitinvv** [comment]
@decarlof @MarkRivers SampleOutAngle=0 doesn't mean that flat fields will be taken as before. This means that flat fields will be taken at 0 degrees at the beginning  or/and at the end of a scan. Users typically check where to take flat fields when the rotary is at 0 and forget to check it for 180 degrees. In this case 'End''/'Both' mode creates potential problems. So this commit will resolve already existing problem in tomoscan.

**Comment by MarkRivers** [comment]
> @decarlof @MarkRivers SampleOutAngle=0 doesn't mean that flat fields will be taken as before. This means that flat fields will be taken at 0 degrees at the beginning or/and at the end of a scan. 

That won't work for us.  We do tomography in a 250 ton press, where the rotation is very slow.  We don't move back to 0 at the end of the scan.  So we need to do what we are doing now, take the flat fields at the beginning at 0 degrees and those at the end at 180 degrees.

A solution that could work for both of us is to have 2 new variables, SampleOutAngleStart, SampleOutAngleEnd.  I would set those to 0 and 180 respectively.  You would set them both to 0.

**Comment by decarlof** [comment]
The difference is really in the meaning we give to start/end. In the current version it refers to motor position, in @nikitinvv version it refers to time (when the scan starts/ends ...) Allowing for only one position to take the flat breaks the ability to collect the data as we do now. @MarkRivers solution solves the issue but I think there still is a small difference in fly scan we should be aware of: currently the flat at the end of the scan is taken after the fly scan is done. The motor position is not the stop position but the stop position plus the deceleration distance. To be fully identical we should default   SampleOutAngleStart to the start angle (not necessarily zero) and the SampleOutAngleEnd to the stop angle plus the PSO calculated deceleration distance.

**Comment by MarkRivers** [comment]
I agree it won't be fully identical.  But we don't want Python to be writing those default values to SampleOutAngleStart and SampleOutAngleEnd because that would overwrite what the user has selected.  It is the user's responsibility to set those correctly.  For me having it rewind a few degrees from the actual end of scan to 180 is fine.

**Comment by MarkRivers** [comment]
Now the question is what should tomoscan do when the user is not scanning, and the stage is at an arbitrary position (say 90 degrees) and the user presses Move Sample Out.  Should it go to SampleOutAngleStart or SampleOutAngleEnd?

**Comment by decarlof** [comment]
> I agree it won't be fully identical. But we don't want Python to be writing those default values to SampleOutAngleStart and SampleOutAngleEnd because that would overwrite what the user has selected. It is the user's responsibility to set those correctly. For me having it rewind a few degrees from the actual end of scan to 180 is fine.

that actually was my question. If you are OK with the small rewind we are good.

**Comment by nikitinvv** [comment]
Then I think the checkbox for manual AngleOut is indeed needed. If manual AngleOut is 'Off' then do what tomoscan did before. In this case the user can press MoveSampleOut at an arbitrary angle and it will move the sample for the current angle. If manual AngleOut is 'On' then it will go to the specified angle and move the sample out. And I think we don't need two angles AngleOutStart and AngleOutEnd in this case

**Comment by decarlof** [comment]
> Now the question is what should tomoscan do when the user is not scanning, and the stage is at an arbitrary position (say 90 degrees) and the user presses Move Sample Out. Should it go to SampleOutAngleStart or SampleOutAngleEnd?

Shall we select by default the closest?  and add an option to select which one to go? I cannot imagine a situation where a SampleOutAngle is the preferred one (no matter the distance to get there) but perhaps there are (cable pulling etc)

**Comment by MarkRivers** [comment]
If I am at 90 degrees and I do MoveSampleOut I really don't want it to rotate, I just want to move it out.

I am thus thinking that a single SampleOutAngle and a binary output record that enables/disables use of that field is what we need, as Viktor said.  That way we can preserve the current behavior with no issues.

**Comment by decarlof** [comment]
The above implements what we discussed. I will test it next machine studies day so please do not merge yet. The medm screen will look like this. Let me know if this is clear enough: 

Screen Shot 2021-11-27 at 10 26 31 AM

**Comment by MarkRivers** [comment]
That looks good to me.

**Comment by aps-7bm** [comment]
If I can add my thoughts, I would agree with Mark that one should not change the angle when one moves the sample out as a default behavior.  This behavior caused some significant problems for me with my current users doing the streaming scans where we just let the stage freely spin.  Especially if you've already spun several rotations, having the angle go back to zero is slow and problematic.  I like Francesco's solution.  It makes the interface a little more complicated but handles all of the relevant cases, I think.

**Comment by decarlof** [comment]
OK the above is fully tested at 32-ID. 
@MarkRivers we added [this](https://github.com/decarlof/tomoscan/blob/e7fad8fe7cdd4b440d5925553ffdadbff544e3e4/tomoscan/tomoscan.py#L225) to initialize control PVs in the 'done' status. It is very rare but I noticed that when the python server crashes at the wrong place it could leave these PVs in the move state. If this happens with the current code, the only way to get out is to restart the epics IOC or to do a caput 0 in that PV (which is not obvious).
if you OK with this, we can merge.

**Review by MarkRivers — COMMENTED** [review]
This looks OK to me with 2 minor issues in tomoscan.py
- Commented out code for aravis at 32-ID
- Added trailing white space in line 708

**Comment by decarlof** [comment]
@MarkRivers for "Commented out code for aravis at 32-ID" you mean removing [line 902](https://github.com/decarlof/tomoscan/blob/eed9a0dfd99d547906caefcc7703cf7b23773fdb/tomoscan/tomoscan.py#L902)?

**Comment by MarkRivers** [comment]
@decarlof 
>you mean removing line 902?

No, I mean lines 577-579.

**Comment by decarlof** [comment]
good thanks!

**Pull request merged**
