### PR TITLE
tomoscan-cli support

### PR DESCRIPTION
**Pull request by decarlof**
This adds support for a tomoscan-cli (#56). Check [Usage](https://mytomoscan.readthedocs.io/en/latest/usage.html#tomoscan-cli) and [Demo](https://mytomoscan.readthedocs.io/en/latest/demo.html#using-the-tomoscan-cli) doc preview pages for the new functionalities. It reproduces what we use at 2-BM for running tomography.

@MarkRivers: the db file location is temporarily set as a parameter [here](https://github.com/decarlof/tomoscan/blob/25c5ea98354fe4702eda1bc2891f31b8b07f0de5/tomoscan/config.py#L30). Is there a better way? One option is to add them to the distribution using [MANIFEST.in](https://packaging.python.org/guides/using-manifest-in/); what is the usual way in EPICS? Is a environment setting?

For now, I also parametrized the [beamline](https://github.com/decarlof/tomoscan/blob/25c5ea98354fe4702eda1bc2891f31b8b07f0de5/tomoscan/config.py#L74) but I think is  better to remove it and clean up [tomoscan](https://github.com/decarlof/tomoscan/blob/master/bin/tomoscan) so import is only for the beamline specific class (?)

### CODE REVIEW

**Comment by MarkRivers** [comment]
(I will have some questions about this, but I'm busy with ALS Proposal Study Panel until Friday.)

**Comment by MarkRivers** [comment]
> @MarkRivers: the db file location is temporarily set as a parameter here. Is there a better way?

What is the db file location used for?  

Do you have an example of a configuration file?

**Comment by MarkRivers** [comment]
It looks like the db/ directory is used as the default location for the log file?  I don't understand that.  Why was that chosen?

**Comment by decarlof** [comment]
Actually I should have looked at the PR before asking you to review it ...  I solved that issue [here](https://github.com/tomography/tomoscan/pull/63/commits/196aac5e1c5416dd94d1d1f073f00e1b77e5813b) by removing line 55-58. In the first version of the cli, I used to start the python server from within the python script, so I needed to know the db file location.  I will remove TOMOSCAN_DB_HOME from the config.py file

**Comment by decarlof** [comment]
> Do you have an example of a configuration file?

```
(py37) user2bmb@pg10ge:~$ more  tomoscan.conf 
[general]
logs-home = /home/user2bmb/logs
verbose = False
sleep = False
in-situ = False
testing = False

[tomoscan]
tomoscan-db-home = /home/user2bmb/epics/synApps/support/tomoscan/db/
tomoscan-prefix = 2bma:TomoScan:
scan-type = mosaic

[in-situ]
# in-situ-pv = 
# in-situ-pv-rbv = 
in-situ-start = 0.0
in-situ-step-size = 1.0
sleep-time = 0.5
sleep-steps = 2

[vertical]
vertical-start = 0.0
vertical-step-size = 0.1
vertical-steps = 5.0

[horizontal]
horizontal-start = 0.0
horizontal-step-size = 0.1
horizontal-steps = 5.0
```

**Comment by MarkRivers** [comment]
Would this line no longer be present in the current version?
```
tomoscan-db-home = /home/user2bmb/epics/synApps/support/tomoscan/db/
```

**Comment by MarkRivers** [comment]
So it looks like the tomoscan-cli is just a Channel Access client that implements scanning.  It interacts with the tomo_scan class through Channel Access, rather than by instantiating a tomo_scan object and calling its methods directly?

**Comment by decarlof** [comment]
> Would this line no longer be present in the current version?
> 
> ```
> tomoscan-db-home = /home/user2bmb/epics/synApps/support/tomoscan/db/
> ```

correct

**Comment by decarlof** [comment]
> So it looks like the tomoscan-cli is just a Channel Access client that implements scanning. It interacts with the tomo_scan class through Channel Access, rather than by instantiating a tomo_scan object and calling its methods directly?

correct. At the end it, was the simplest thing to do to reproduce the same cli the 2-BM users are familiar with. This way users can also freely go back and forth between running a single scan from the medm screen or running a mosaic/vertical scan with the cli without having to worry about starting the python server (which is the same and always running).

**Comment by MarkRivers** [comment]
Looks good, I am happy for you to merge this.

**Comment by decarlof** [comment]
Also in much cleaner on the log messages (each server has its own place)

**Comment by decarlof** [comment]
> Looks good, I am happy for you to merge this.

good, thanks

**Pull request merged**
