### PR TITLE
tomoscan_pso returning theta[]

### PR DESCRIPTION
**Pull request by decarlof**
@MarkRivers are you ok adding [this](https://github.com/decarlof/tomoscan/blob/8e32979f5ec9426d5c8e4b97714cc3bc192cbe12/tomoscan/tomoscan_pso.py#L308) in tomoscan_pso? At one point, I'd like to add in the same compute_positions_PSO() options for interlaced angular positions as described in #103

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
Computing theta is fine with me. 

I don't understand the need for the commented line 95.

**Comment by decarlof** [comment]
> I don't understand the need for the commented line 95

my mistake

**Comment by decarlof** [comment]
I am also ready to remove the [PSO entries](https://github.com/tomography/tomoscan/blob/1db28bdf95524ae089404cdf2b704e41458436e4/tomoscan/tomoscan.py#L177) from tomoscan.py if @aps-7bm is OK with it.

**Comment by aps-7bm** [comment]
Sure, go ahead

**Pull request merged**
