### PR TITLE
Added tomoscan IOC support to all TXM PVs

### PR DESCRIPTION
**Pull request by decarlof**
- adds tomoscan IOC support to all TXM PVs
- docs update
- aerotech configuration

work in progress: finalizing tomoscan_32id.py

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
It seems like the additions to tomoscan.py are very specific to 32-ID.  Can they be move to the tomoscan_32-id class instead.  tomoscan.py should contain things that are likely to be used on multiple beamlines.

**Comment by decarlof** [comment]
@MarkRivers thanks for the suggestion, it is implemented.

I'll keep this open for another couple of days till I finish step and interlaced scans for 32-ID.

**Review by MarkRivers — COMMENTED** [review]
It looks the PV definitions have been added to lines 41-100 in to __init__ tomoscan_32id.py.  But they have not yet been removed from tomoscan.py.

It seems like this line may need to be added to tomoscan_32id.py at line 101.
```
 self.epics_pvs = {**self.config_pvs, **self.control_pvs}
```

**Comment by decarlof** [comment]
@MarkRivers it looks I forgot to stage tomoscan.py. Should be ok now. I will also add the missing

 ```self.epics_pvs = {**self.config_pvs, **self.control_pvs}``` 

thanks

**Comment by decarlof** [comment]
@MarkRivers I am ready to merge. Actually I should have merged earlier ... I started to work on 6-BM and now there are mixed commits.  After this is merged, I will set 6-BM to work on its own fork, so we avoid this situation in the future and @cpchuang can complete the 6-BM customization independently.

**Pull request merged**
