### PR TITLE
adding tomoScanStream support for 7-BM

### PR DESCRIPTION
**Pull request by decarlof**
plus other improvements at 32-ID.

@MarkRivers The only change in tomoscan.py is the reset of the image unique ID 

 `self.epics_pvs['CamArrayCounter'].put(0, wait=True)`
 
@MarkRivers this is needed for the Blackfly S BFS-PGE-161S7M at 32-ID (other camera starts from zero at acquisition start). We need this to handle missing frames the same way for all camera. 
 
 Let me know if this is a setting we can add to the camera instead than in tomoscan.py,

### CODE REVIEW

**Comment by MarkRivers** [comment]
> @MarkRivers this is needed for the Blackfly S BFS-PGE-161S7M at 32-ID (other camera starts from zero at acquisition start). We need this to handle missing frames the same way for all camera.

I suspect the problem is that the driver is not configured to get the UniqueID from the camera, but rather is using the driver.  I believe all FLIR cameras reset the UniqueID to 0 at the beginning of each acquisition.  Please attach a screen shot of the camera screen.

I would like to avoid putting this logic in tomoscan.py if possible.

**Comment by decarlof** [comment]
correct all FLIR we have so far reset the unique ID to zero at the beginning of the scan except this one. 

Below is the main camera control screen:

Screen Shot 2021-11-15 at 1 34 20 PM
e

**Comment by MarkRivers** [comment]
So they are running ADAravis, not ADSpinnaker.  I am not sure that ADAravis supports embedding the UniqueID.  Is there a reason they are not using ADSpinnaker?

**Comment by MarkRivers** [comment]
Using this approach with ADAravis will only tell you that you have dropped frames, it will not tell you which frames are dropped.  That is because it is setting the UniqueID based on the number of images received so far from the camera.  So if you are collecting 1800 frames and only 1799 are received, the UniqueID of the final frame will always be 1799.  

On the other hand, if you are using ADSpinnaker, the UniqueID is generated inside the camera, and the UniqueID of the final frame will probably be 1800.  You can use the UniqueID of each frame to determine which one is missing.

**Comment by decarlof** [comment]
Thank you Mark, we will try to get the ADSpinnaker installed. For now I will remove the changes in tomoscan.py and, if the rest looks OK, will merge

**Comment by MarkRivers** [comment]
The rest looks fine to me, please merge.

**Comment by nikitinvv** [comment]
@MarkRivers Aravis simply does not allow us to handle missing frames... this is ridiculous. I need to switch the blackfly camera to spinnaker

**Pull request merged**
