### PR TITLE
Tomoscan pso

### PR DESCRIPTION
**Pull request by MarkRivers**
This is draft PR for a work in progress.

I have created a new intermediate class, TomoScanPSO in the file tomoscan_pso.py.  This class implements scanning using the PSO feature of the Aerotech controllers.  It basically takes many of the the methods from tomoscan_7bm.py and moves them to a new base class.  This keeps tomoscan.py independent of the PSO hardware, but provides a class that 2-BM, 7-BM, 13-BM can use and greatly reduce the code in their beamline specific classes. 

The new tomoscan_13bm_pso class in fact only uses the base class methods.  

tomoscan_7bm has been reduced to 30% of its previous size.  

This has not yet been tested at all.

### CODE REVIEW

**Comment by MarkRivers** [comment]
@aps-7bm I have a question and a comment.

Question:
The tomoscan_7bm.template has startTaxi and endTaxi PVs.  Is there a good reason for these to be PVs?  It appears that these are just used as essentially local variables.  The values are computed in compute_positions_PSO and used in collect_projections.  Is there any need for these to be visible in EPICS?  If so, should only the readback be visible, since the user should not be changing these values?

Comment:
The tomoscan_7bm.template has a PV that holds the name of an asyn record that is used to communicate with the Aerotech controller, but it does not contain the asyn record itself.  The disadvantage of this approach is that new users (like me) don't have any indication of how that asyn record should be configured.  Should it be using ASCII, Hybrid, or Binary input mode and output mode?  Should it be using Write or Write/Read transfer mode?  I think it would be better to have the PSO template file contain the actual asyn record.  That way we can specify how the fields should be configured.  This would have the effect of making IOCs that use tomoscan_pso depend on the asyn module, which currently is optional and commented out.  But I think the clarity is worth it.  Thoughts?

**Comment by aps-7bm** [comment]
You have a fair point on the startTaxi and endTaxi PVs.  This is partially
a vestige of how Tim Mooney had the PSO code set up.  These wouldn't be
something a user would set, so they could be made read-only, and perhaps
should be removed entirely.  They may be useful if one were to couple this
with a scan record, since those positions would be what one would use for
the start and end values for the scan.  One thing I like about having them
is that users can know exactly where the stage is moving.

In terms of the asyn record, my only concern would be whether that would
mess up how the stage is set up in my VME crate right now.  I suppose it
could work if the only time I ever communicate with the stage is through
tomoScan, but it would be weird to have one motor not run through the same
IOC as everything else.  Perhaps I am being silly; I am open to ideas.

**Comment by MarkRivers** [comment]
I will make the taxi PVs read-only and change their names to be consistent with the others in the file (i.e. start with PSO).

On further thought, using an external asyn record as @aps-7bm has done seems like the better option.  If that record is in the motor IOC and if asynTrace is enabled then all communication with the controller will be seen.  If it were put in the tomoScan IOC then two IOCs would be communicating with the controller, which is less desirable. 

@aps-7bm can you post screen shots of your asynRecord (asynRecord.adl, asynOctet.adl) so I can see how it is configured?  I can then document that in tomoscan_pso.template.

**Comment by aps-7bm** [comment]
[image: image.png]
Is this what you want?

**Comment by aps-7bm** [comment]
Is this what you want?
[image: image.png]

**Comment by MarkRivers** [comment]
@aps-7bm those images did not get posted.  I think you replied by e-mail, rather than directly posting to Github.  They did not show up in my e-mail either.

**Comment by decarlof** [comment]
@MarkRivers this gives me a good idea of how I should have structured tomostream. I will look at redoing that so tomostream can be added more easily to other beamlines too.  Just 2 quick questions:
Should:
 - tomoScan_pso.adl named tomoScan_13BM_PSO.adl
 - in the PV in tomoScan_pso.adl the Rotation start/end taxi PV be _RBV

**Comment by decarlof** [comment]
I think is not automatically merging because [this](https://github.com/tomography/tomoscan/commit/db737ced5968b6fb636e14a707245fa15bbd18f5) is conflicting with [this](https://github.com/tomography/tomoscan/commit/042993bc710a148f970851b136d2739e76054f2d). I basically replaced the print with log messages sometime after your branch. We can take them out completely but @aps-7bm put them there so I wasn't sure

**Comment by MarkRivers** [comment]
I merged master into the tomoscan_pso branch and fixed the conflict.  I left in the warning when exposure_time is None and removed the other print/info.log.

**Comment by MarkRivers** [comment]
It appears that the Ensemble does not support the UNITSTOCOUNTS command.  I have changed the code as follows:
- The PSO_ENC_PER_ROTATION macro is now a signed number.  The sign replaces the previous encoder_sign variable in the Python code.  This removes a device dependency from the code.
- On the A3200 the value of PSO_ENC_PER_ROTATION is ignored and it reads the value from the controller, which includes the sign.

**Comment by MarkRivers** [comment]
I added a new PV, PSOPulseWidth, which is the pulse width in microseconds.  I found that it needed to be 50 for my camera.  Using a PV to configure it removes a device dependency from the Python code.

**Comment by MarkRivers** [comment]
I believe I have made all of the changes that are required to the 2BM and 7BM classes, iocBoot files, and medm screens to use this branch.  At a minimum you will need to edit st.cmd to set the correct IP address or IP name for your Ensemble controller.

In this branch the synApps asyn module is no longer optional, it is required.  You can clone from Github and checkout the latest tag, R4-41.  You can edit asyn/configure/RELEASE and comment out the lines for IPAC and SNCSEQ.  The lines for CALC and SSCAN should already be commented out.  If you do this then asyn will depend only on EPICS base.

I am ready for this PR to be merged.

**Comment by MarkRivers** [comment]
I have not done anything with the documentation yet.

**Comment by decarlof** [comment]
@MarkRivers I suggest to merge this now and add the docs later. There are a couple of very minor conflicts with #97 that is easier to solve after the merge.

**Comment by MarkRivers** [comment]
I have done most of the required work on the docs.  The only thing that I know still needs to be done is update tomoScanApp.rst.

**Pull request merged**
